# Generated by Django 3.0.6 on 2020-06-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='button_info',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
