# Generated by Django 3.0.6 on 2020-05-27 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userposts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=200, null=True)),
                ('like_comments', models.PositiveIntegerField(blank=True, null=True)),
                ('remove_comments', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userposts.UserPosts')),
            ],
        ),
    ]
