# Generated by Django 3.0.6 on 2020-06-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messagefrom', models.PositiveIntegerField(blank=True, null=True)),
                ('messageto', models.PositiveIntegerField(blank=True, null=True)),
                ('messagetext', models.CharField(max_length=2000, null=True)),
                ('like_message', models.PositiveIntegerField(blank=True, null=True)),
                ('remove_message', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
            ],
        ),
    ]
